spring:
  redis:
    host: 192.168.188.128
    port: 6579
    password:
    jedis:
      pool:
        #最大连接数
        max-active: 8
        #最多阻塞等待时间 -1 表示没有限制
        max-wait: -1
        #最大空闲
        max-idle: 8
        #最小空闲连接数
        min-idle: 0
    #连接超时时间 mm
    timeout: 10000
